// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/countries": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Список стран",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Country"
                            }
                        }
                    }
                }
            }
        },
        "/leagues": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Список лиг страны за определенный сезон",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID страны (напр. 141)",
                        "name": "country",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Период сезона (напр. 2019)",
                        "name": "season_period",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.League"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorJSON"
                        }
                    },
                    "408": {}
                }
            }
        },
        "/player_detail": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Карточка игрока",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL игрока",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PlayerDetail"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorJSON"
                        }
                    },
                    "408": {}
                }
            }
        },
        "/seasons": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Список сезонов с 1900г. по текущий",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Season"
                            }
                        }
                    }
                }
            }
        },
        "/team_compositions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Список команд и игроков в них по соревнованию (лига \u0026 сезон)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL соревнования",
                        "name": "league_url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Team"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorJSON"
                        }
                    },
                    "408": {}
                }
            }
        }
    },
    "definitions": {
        "models.Country": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "В доработке",
                    "type": "string",
                    "example": "Russia"
                },
                "id": {
                    "type": "integer",
                    "example": 141
                },
                "name": {
                    "type": "string",
                    "example": "Russia"
                }
            }
        },
        "models.ErrorJSON": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "models.League": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 17201
                },
                "logo": {
                    "type": "string",
                    "x-nullable": true,
                    "example": "https://tmssl.akamaized.net/images/logo/normal/ru1.png?lm=1582769594"
                },
                "position": {
                    "type": "string",
                    "example": "First Tier"
                },
                "title": {
                    "type": "string",
                    "example": "Premier Liga"
                },
                "url": {
                    "type": "string",
                    "example": "https://transfermarkt.com/premier-liga/startseite/wettbewerb/RU1"
                }
            }
        },
        "models.Player": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 15570
                },
                "url": {
                    "type": "string",
                    "example": "https://transfermarkt.com/igor-akinfeev/profil/spieler/15570"
                }
            }
        },
        "models.PlayerDetail": {
            "type": "object",
            "properties": {
                "age": {
                    "description": "nullable",
                    "type": "integer",
                    "example": 24
                },
                "birth_country": {
                    "description": "nullable",
                    "type": "integer",
                    "example": 9
                },
                "birth_date": {
                    "description": "nullable",
                    "type": "string",
                    "example": "Feb 10, 1996"
                },
                "contract_expires": {
                    "type": "string"
                },
                "contract_rental_expires": {
                    "type": "string"
                },
                "contracts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "http://www.instagram.com/emanuel_mammana24/"
                    ]
                },
                "country": {
                    "description": "nullable",
                    "type": "integer",
                    "example": 9
                },
                "country_2": {
                    "description": "Nullable",
                    "type": "integer",
                    "example": 75
                },
                "current_club": {
                    "type": "integer",
                    "example": 964
                },
                "current_rental": {
                    "type": "integer"
                },
                "height": {
                    "description": "nullable",
                    "type": "integer",
                    "example": 183
                },
                "image_url": {
                    "type": "string",
                    "example": "https://tmssl.akamaized.net/images/portrait/header/275512-1572532565.png?lm=1572532580"
                },
                "name": {
                    "type": "string",
                    "example": "Emanuel Mammana"
                },
                "position": {
                    "type": "string",
                    "example": "Defender - Centre-Back"
                },
                "shock_foot": {
                    "type": "string",
                    "example": "right"
                }
            }
        },
        "models.Season": {
            "type": "object",
            "properties": {
                "period": {
                    "type": "integer",
                    "example": 2019
                },
                "season_end": {
                    "type": "string",
                    "example": "30-06-2020"
                },
                "season_start": {
                    "type": "string",
                    "example": "01-07-2019"
                }
            }
        },
        "models.Team": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 2410
                },
                "players": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Player"
                    }
                },
                "title": {
                    "type": "string",
                    "example": "CSKA Moscow"
                },
                "url": {
                    "type": "string",
                    "example": "https://transfermarkt.com/zska-moskau/startseite/verein/2410/saison_id/2019"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
