// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package slices

func String_Last(slice []string) string {
	return slice[len(slice)-1]
}
